/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTreeRouteImport } from './routes/_app.tree'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppKinRouteImport } from './routes/_app.kin'
import { Route as AppHomeRouteImport } from './routes/_app.home'
import { Route as AppGalleryRouteImport } from './routes/_app.gallery'
import { Route as AppExploreRouteImport } from './routes/_app.explore'
import { Route as AppAddFamilyRouteImport } from './routes/_app.add-family'
import { Route as AppExplorePostIdRouteImport } from './routes/_app.explore.$postId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTreeRoute = AppTreeRouteImport.update({
  id: '/tree',
  path: '/tree',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppKinRoute = AppKinRouteImport.update({
  id: '/kin',
  path: '/kin',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppGalleryRoute = AppGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AppRoute,
} as any)
const AppExploreRoute = AppExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AppRoute,
} as any)
const AppAddFamilyRoute = AppAddFamilyRouteImport.update({
  id: '/add-family',
  path: '/add-family',
  getParentRoute: () => AppRoute,
} as any)
const AppExplorePostIdRoute = AppExplorePostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => AppExploreRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/add-family': typeof AppAddFamilyRoute
  '/explore': typeof AppExploreRouteWithChildren
  '/gallery': typeof AppGalleryRoute
  '/home': typeof AppHomeRoute
  '/kin': typeof AppKinRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/tree': typeof AppTreeRoute
  '/explore/$postId': typeof AppExplorePostIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/add-family': typeof AppAddFamilyRoute
  '/explore': typeof AppExploreRouteWithChildren
  '/gallery': typeof AppGalleryRoute
  '/home': typeof AppHomeRoute
  '/kin': typeof AppKinRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/tree': typeof AppTreeRoute
  '/explore/$postId': typeof AppExplorePostIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/_app/add-family': typeof AppAddFamilyRoute
  '/_app/explore': typeof AppExploreRouteWithChildren
  '/_app/gallery': typeof AppGalleryRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/kin': typeof AppKinRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/tree': typeof AppTreeRoute
  '/_app/explore/$postId': typeof AppExplorePostIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/add-family'
    | '/explore'
    | '/gallery'
    | '/home'
    | '/kin'
    | '/notifications'
    | '/profile'
    | '/tree'
    | '/explore/$postId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/add-family'
    | '/explore'
    | '/gallery'
    | '/home'
    | '/kin'
    | '/notifications'
    | '/profile'
    | '/tree'
    | '/explore/$postId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/admin'
    | '/auth'
    | '/_app/add-family'
    | '/_app/explore'
    | '/_app/gallery'
    | '/_app/home'
    | '/_app/kin'
    | '/_app/notifications'
    | '/_app/profile'
    | '/_app/tree'
    | '/_app/explore/$postId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/tree': {
      id: '/_app/tree'
      path: '/tree'
      fullPath: '/tree'
      preLoaderRoute: typeof AppTreeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kin': {
      id: '/_app/kin'
      path: '/kin'
      fullPath: '/kin'
      preLoaderRoute: typeof AppKinRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gallery': {
      id: '/_app/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof AppGalleryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/explore': {
      id: '/_app/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AppExploreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/add-family': {
      id: '/_app/add-family'
      path: '/add-family'
      fullPath: '/add-family'
      preLoaderRoute: typeof AppAddFamilyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/explore/$postId': {
      id: '/_app/explore/$postId'
      path: '/$postId'
      fullPath: '/explore/$postId'
      preLoaderRoute: typeof AppExplorePostIdRouteImport
      parentRoute: typeof AppExploreRoute
    }
  }
}

interface AppExploreRouteChildren {
  AppExplorePostIdRoute: typeof AppExplorePostIdRoute
}

const AppExploreRouteChildren: AppExploreRouteChildren = {
  AppExplorePostIdRoute: AppExplorePostIdRoute,
}

const AppExploreRouteWithChildren = AppExploreRoute._addFileChildren(
  AppExploreRouteChildren,
)

interface AppRouteChildren {
  AppAddFamilyRoute: typeof AppAddFamilyRoute
  AppExploreRoute: typeof AppExploreRouteWithChildren
  AppGalleryRoute: typeof AppGalleryRoute
  AppHomeRoute: typeof AppHomeRoute
  AppKinRoute: typeof AppKinRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppTreeRoute: typeof AppTreeRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAddFamilyRoute: AppAddFamilyRoute,
  AppExploreRoute: AppExploreRouteWithChildren,
  AppGalleryRoute: AppGalleryRoute,
  AppHomeRoute: AppHomeRoute,
  AppKinRoute: AppKinRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppTreeRoute: AppTreeRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
